@ImageLinks.Api_HostAddress = http://localhost:5272

### Get all users
GET {{ImageLinks.Api_HostAddress}}/api/users
Accept: application/json

### Get user by id
GET {{ImageLinks.Api_HostAddress}}/api/users/1
Accept: application/json

### Create user
POST {{ImageLinks.Api_HostAddress}}/api/users
Content-Type: application/json
Accept: application/json

{
  "userName": "sample-user",
  "password": "P@ssw0rd!"
}

### Update user
PUT {{ImageLinks.Api_HostAddress}}/api/users/1
Content-Type: application/json

{
  "userName": "updated-user",
  "password": "N3wP@ssw0rd!"
}

### Delete user
DELETE {{ImageLinks.Api_HostAddress}}/api/users/1
